name: Delete Workflow Runs

on:
  workflow_dispatch:  # 수동 트리거를 허용

jobs:
  delete-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get install jq

      - name: Delete Workflow Runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 모든 워크플로우 실행 기록 가져오기
          runs=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                       -H "Accept: application/vnd.github+json" \
                       "https://api.github.com/repos/${{ github.repository }}/actions/runs" \
                       | jq '.workflow_runs[].id')

          # 실행 기록 삭제
          for run_id in $runs; do
              echo "Deleting workflow run ID: $run_id"
              curl -X DELETE -s -H "Authorization: token $GITHUB_TOKEN" \
                  -H "Accept: application/vnd.github+json" \
                  "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id"
          done

          echo "All workflow runs deleted."
