name: Update CSV Files

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * *"  # 매일 12시에 실행 (UTC)

permissions:
  contents: write  # 저장소 변경 권한 부여

jobs:
  update-csv:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install pandas requests yfinance

      - name: Set git config for commit
        run: |
          git config --global user.email "your-email@example.com"  # Git 이메일 설정
          git config --global user.name "Your Name"  # Git 사용자 이름 설정

      - name: Remove outdated CSV files
        run: |
          files_to_remove=("KOSPI.csv" "USD_KRW.csv" "동행지수순환변동치.csv" "선행지수순환변동치.csv")
          for file in "${files_to_remove[@]}"; do
            if [ -f "$file" ]; then
              git rm "$file"  # 파일 삭제
              echo "$file removed."
            else
              echo "$file does not exist."
            fi
          done
          git commit -m "Remove outdated CSV files" || echo "No files to remove"  # 변경 사항 없으면 메시지 출력

      - name: Run Python script
        run: |
          python script.py || exit 1  # 스크립트 실패 시 명시적으로 오류 처리

      - name: Add and commit new CSV files
        run: |
          git add $(find . -name "*.csv")  # 모든 CSV 파일 추가
          git commit -m "Update CSV files" || echo "No changes to commit"  # 변경 사항 없으면 메시지 출력

      - name: Push changes
        run: |
          git push || echo "Nothing to push"  # 변경 사항이 없을 경우 메시지 출력
