name: Update CSV Files and Generate Chart

on:
  push:
    branches:
      - main
  schedule:
    - cron: "10 0 * * *"  # 매일 자정 10분에 실행 (UTC)

permissions:
  contents: write  # 저장소 변경 권한 부여

jobs:
  update-and-generate:
    runs-on: ubuntu-22.04

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      # 2. Git 설정
      - name: Set git config for commit
        run: |
          git config --global user.email "injea100@gmail.com"
          git config --global user.name "Sanghoon-ai"

      # 3. 기존 CSV 파일 제거
      - name: Remove outdated CSV files
        run: |
          files_to_remove=("KOSPI_add.csv" "USD_KRW_add.csv" "동행지수순환변동치_add.csv" "선행지수순환변동치_add.csv")
          for file in "${files_to_remove[@]}"; do
            if [ -f "$file" ]; then
              git rm "$file"
              echo "$file removed."
            else
              echo "$file does not exist."
            fi
          done
          git commit -m "Remove outdated CSV files" || echo "No files to remove"

      # 4. Python 환경 설정 및 의존성 설치
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies for CSV update
        run: |
          pip install pandas requests yfinance

      # 5. CSV 업데이트 스크립트 실행
      - name: Run Python script for updating CSV
        run: |
          python script.py || exit 1

      # 6. 변경된 CSV 파일 커밋 및 푸시
      - name: Add and commit new CSV files
        run: |
          git add $(find . -name "*.csv")
          git commit -m "Update CSV files" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push || echo "Nothing to push"

      # 7. Chart 생성용 의존성 설치
      - name: Install dependencies for chart generation
        run: |
          pip install pandas requests plotly yfinance

      # 8. Chart 생성 스크립트 실행
      - name: Run Python script to generate chart
        run: |
          python view_chart.py

      # 9. Chart 파일 커밋 및 푸시
      - name: Add and commit chart.html
        run: |
          git add chart_files/chart.html
          git commit -m "Update chart_files/chart.html file" || echo "No changes to commit"

      - name: Push chart changes to repository
        run: |
          git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main || echo "Nothing to push"
