name: Update CSV Files

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * *"  # 매일 12시에 실행 (UTC)

permissions:
  contents: write  # 저장소 변경 권한 부여

jobs:
  run-script:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install pandas requests yfinance

      - name: Remove KOSPI.csv file
        run: |
          if [ -f "KOSPI.csv" ]; then
            git rm KOSPI.csv  # KOSPI.csv 파일 삭제
            git commit -m "Remove KOSPI.csv file"  # 파일 삭제 커밋
            git push  # 변경 사항 푸시
          else
            echo "KOSPI.csv 파일이 존재하지 않습니다."
          fi

      - name: Run Python script
        run: |
          python script.py || exit 1  # 스크립트 실패 시 명시적으로 오류 처리

      - name: Check for changes and commit
        run: |
          git status  # 파일 상태 확인
          git add $(find . -name "*.csv")  # 모든 CSV 파일을 추가
          git status  # 변경된 파일 확인
          git commit -m "Update CSV files" || echo "No changes to commit"  # 변경된 파일이 없으면 메시지 출력
          git push
