name: Update CSV Files

on:
  push:
    branches:
      - main
  schedule:
    - cron: "10 0 * * *"  # 매일 자정 10분에 실행 (UTC)

permissions:
  contents: write  # 저장소 변경 권한 부여

jobs:
  update-csv:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}  # GitHub Personal Access Token 사용

      - name: Set git config for commit
        run: |
          git config --global user.email "injea100@gmail.com"
          git config --global user.name "Sanghoon-ai"

      - name: Remove outdated CSV files
        run: |
          files_to_remove=("KOSPI_add.csv" "USD_KRW_add.csv" "동행지수순환변동치_add.csv" "선행지수순환변동치_add.csv")
          for file in "${files_to_remove[@]}"; do
            if [ -f "$file" ]; then
              git rm "$file"
              echo "$file removed."
            else
              echo "$file does not exist."
            fi
          done
          git commit -m "Remove outdated CSV files" || echo "No files to remove"

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install pandas requests yfinance

      - name: Run Python script
        run: |
          python script.py || exit 1

      - name: Add and commit new CSV files
        run: |
          git add $(find . -name "*.csv")
          git commit -m "Update CSV files" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push || echo "Nothing to push"

      - name: Trigger view_chart.yml workflow
        run: |
          echo "Triggering view_chart.yml workflow after main.yml finishes"
          gh workflow run view_chart.yml
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
