name: Generate Chart

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 0 * * *'  # 매일 자정 30분(UTC)에 실행

jobs:
  generate_chart:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install pandas requests plotly

    - name: Print working directory and list files
      run: |
        pwd
        ls -l

    - name: Run Python script to generate chart
      run: |
        python view_chart.py

    - name: Commit and push chart
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git status  # Check if there are any changes
        git add chart.html
        git commit -m "Update chart"
        git push
